import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const unica77 = localFont({
  src: [
    {
      path: '../../public/fonts/Unica77 Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Unica77 Light Italic.ttf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../../public/fonts/Unica77 Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Unica77 Regular Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/fonts/Unica77 Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Unica77 Medium Italic.ttf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../../public/fonts/Unica77 Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Unica77 Bold Italic.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-unica77',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={unica77.variable}>
      <body className={unica77.className}>
        {children}
      </body>
    </html>
  );
}
